export enum ContentType {
    JSON = "application/json",
    XML = "application/xml",
    HTML = "text/html",
    PlainText = "text/plain",
    CSS = "text/css",
    JavaScript = "application/javascript",
    FormURLEncoded = "application/x-www-form-urlencoded",
    MultipartFormData = "multipart/form-data",
    PNG = "image/png",
    JPEG = "image/jpeg",
    GIF = "image/gif",
    SVG = "image/svg+xml",
    WebP = "image/webp",
    PDF = "application/pdf",
    ZIP = "application/zip",
    GZIP = "application/gzip",
    CSV = "text/csv",
    Markdown = "text/markdown",
    EventStream = "text/event-stream",
    OctetStream = "application/octet-stream",
}
